# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: install simplehttpserver package
  apt:
    name:
      - python3
    state: present
  become: true

- name: set http server systemd unit content
  set_fact:
    http_fileserver_unit_content: |
      [Unit]
      Description=Simple http server
      After=syslog.target

      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 -m http.server {{ http_fileserver_serve_port }}
      StandardOutput=syslog
      StandardError=syslog
      WorkingDirectory={{ http_fileserver_serve_dir }}

      [Install]
      WantedBy=multi-user.target

- name: Create systemd unit
  copy:
    content: "{{ http_fileserver_unit_content }}"
    dest: /etc/systemd/system/simple-http-{{ http_fileserver_name | default('default') }}.service
  notify:
    - reload systemd configuration
    - http file server restarted
  become: true

