resources:
  - ../../shared/clusterctl
  - ../../../../function/baremetal-operator
  - ../../../../function/helm-operator
patchesStrategicMerge:
  - patch_bmo_config.yaml
commonLabels:
  airshipit.org/stage: initinfra
