# Site-level host catalogue.  This info feeds the Templater
# kustomize plugin config in the hostgenerator-m3 function.
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: host-catalogue
hosts:
  m3:
    node49:
      bootMode: UEFI
      macAddress: 24:6E:96:51:F4:48
      bmcAddress: redfish+https://192.168.110.49/redfish/v1/Systems/System.Embedded.1
      bmcUsername: username
      bmcPassword: password
      ipAddresses:
        oam-ipv4: 100.82.39.149
        pxe-ipv4: 192.168.121.49
        eno4-ipv4: 192.168.110.149
      macAddresses:
        oam: 24:6E:96:51:F4:28
        pxe: 24:6E:96:51:F4:48
        eno4: 24:6E:96:51:F4:49
      hardwareProfile: default # defined in the hostgenerator-m3 function
    node52:
      bootMode: UEFI
      macAddress: 24:6E:96:51:74:9A
      bmcAddress: redfish+https://192.168.110.52/redfish/v1/Systems/System.Embedded.1
      bmcUsername: username
      bmcPassword: password
      ipAddresses:
        oam-ipv4: 100.82.39.152
        pxe-ipv4: 192.168.121.52
        eno4-ipv4: 192.168.110.152
      macAddresses:
        oam: 24:6E:96:51:74:7A
        pxe: 24:6E:96:51:74:9A
        eno4: 24:6E:96:51:74:9B
      hardwareProfile: default # defined in the hostgenerator-m3 function
    node02:
      bootMode: UEFI
      macAddress: 24:6E:96:53:05:BC
      bmcAddress: redfish+https://192.168.110.48/redfish/v1/Systems/System.Embedded.1
      bmcUsername: username
      bmcPassword: password
      ipAddresses:
        oam-ipv4: 100.82.39.148
        pxe-ipv4: 192.168.121.48
        eno4-ipv4: 192.168.110.148
      macAddresses:
        oam: 24:6E:96:53:05:9C
        pxe: 24:6E:96:53:05:BC
        eno4: 24:6E:96:53:05:BD
      hardwareProfile: example # defined in the hardwareprofile-example function

