apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../global/crd/cluster-api
- https://github.com/kubernetes-sigs/cluster-api/config/default/?ref=v0.3.2

namePrefix: capi-

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: system
  path: patch_namespace.yaml
