apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-controllers-role.yaml
  - kube-controllers-service-account.yaml
  - node-rolebinding.yaml
  - node-service-account.yaml
