apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - baremetalhost.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: node03-netdata
    files:
      - networkData
  - name: node03-bmc
    literals:
      - username=root
      - password=r00tme
