---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: Metal3MachineTemplate
metadata:
  name: cluster-controlplane
spec:
  template:
    spec:
      image:
        url: http://192.168.110.153:8099/target-image.qcow2
        checksum: http://192.168.110.153:8099/target-image.qcow2.md5sum
